spring.application.name=bms_app

spring.datasource.url=jdbc:mysql://localhost:3306/bms_db
spring.datasource.username=root
spring.datasource.password=My_Sql@050

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=soL]z[9vCxI)85s.kx@!SCn+H<mV[cOx.2FIbj@J//q
jwt.expiration=86400000

# Set debug logging for application packages so our added log.debug() calls are visible
logging.level.com.bms.bms_app=DEBUG
